// Golden-vector differential test — the correctness gate.
//
// Runs every exported indicator kernel from src/core.js against the
// committed reference vectors in tests/golden/fixtures.json (generated by
// tests/golden/generate.py: independent numpy/pandas references, a `ta`
// cross-check layer, hand-derived tiny10 vectors — see docs/correctness.md).
//
// The fixtures are rounded to 12 significant digits, so the tolerance below
// only has to absorb that rounding plus float64 summation-order drift
// (measured ≤ ~1e-12 relative); a real regression moves values orders of
// magnitude further. If a convention deliberately changes, regenerate the
// fixtures and say why in the commit — the diff IS the correctness
// conversation.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import * as core from '../src/core.js';

const RTOL = 1e-9;
const ATOL = 1e-12;

const { meta, inputs, cases } = JSON.parse(
  readFileSync(new URL('./golden/fixtures.json', import.meta.url), 'utf8')
);

// Kernels whose signature takes a plain close/values array, not bars. Their
// fixtures store the bars input (same walk150 dataset as the bar-based
// kernels); the closes are extracted here.
const CLOSE_BASED = new Set([
  'calcSMA', 'calcEMA', 'calcWMA', 'calcStdDev', 'calcRSI', 'calcBollinger', 'calcMACD',
  'calcRealizedVol', 'shapeSearch',
]);

const resolveInput = (c) => {
  const inp = inputs[c.input];
  if (inp.kind === 'values') return inp.values;
  return CLOSE_BASED.has(c.fn) ? inp.bars.map((b) => b.close) : inp.bars;
};

const drifts = [];

/**
 * Compare a produced series against its golden vector: same length, null
 * positions identical, numbers within ATOL + RTOL·|ref|.
 * @returns {number} the largest combined-tolerance ratio used (1.0 = at the
 *   limit), 0 when only nulls are compared
 */
function compareSeries(id, name, got, want) {
  assert.ok(Array.isArray(got), `${id}/${name}: kernel returned no array`);
  assert.equal(got.length, want.length, `${id}/${name}: length ${got.length} ≠ ${want.length}`);
  let worst = 0;
  let worstAt = -1;
  for (let i = 0; i < want.length; i++) {
    const w = want[i];
    const g = got[i];
    const wNull = w === null || Number.isNaN(w);
    const gNull = g === null || Number.isNaN(g);
    if (wNull || gNull) {
      assert.equal(gNull, wNull, `${id}/${name}[${i}]: null-ness mismatch (got ${g}, want ${w})`);
      continue;
    }
    const limit = ATOL + RTOL * Math.abs(w);
    const ratio = Math.abs(g - w) / limit;
    if (ratio > worst) {
      worst = ratio;
      worstAt = i;
    }
    assert.ok(
      Math.abs(g - w) <= limit,
      `${id}/${name}[${i}]: got ${g}, want ${w} (Δ ${Math.abs(g - w).toExponential(3)}, ` +
        `tolerance ${limit.toExponential(3)})`
    );
  }
  if (worstAt >= 0) drifts.push({ id: `${id}/${name}`, ratio: worst });
  return worst;
}

for (const c of cases) {
  test(`golden: ${c.fn} ${c.params.length ? c.params.join(',') : ''} — ${c.id} (${c.note})`, () => {
    const fn = core[c.fn];
    assert.ok(typeof fn === 'function', `${c.fn} is not exported from core.js`);
    const out = fn(resolveInput(c), ...c.params);
    for (const [name, want] of Object.entries(c.expected)) {
      if (name === 'shape') {
        // shapeSearch returns a ranked match list, not a series: starts must
        // match exactly (they are integer indices), scores/distances within
        // tolerance — the FFT path vs the brute-force reference
        assert.ok(Array.isArray(out), `${c.id}: kernel returned no match list`);
        assert.equal(out.length, want.length, `${c.id}: match count ${out.length} ≠ ${want.length}`);
        for (let i = 0; i < want.length; i++) {
          assert.equal(out[i].start, want[i].start, `${c.id}.match[${i}].start`);
          for (const k of ['score', 'distance']) {
            const limit = ATOL + RTOL * Math.abs(want[i][k]);
            assert.ok(
              Math.abs(out[i][k] - want[i][k]) <= limit,
              `${c.id}.match[${i}].${k}: got ${out[i][k]}, want ${want[i][k]}`
            );
          }
        }
        continue;
      }
      if (name === 'bars') {
        // calcHeikinAshi returns bar objects, not series
        assert.equal(out.length, want.length, `${c.id}: bars length`);
        for (let i = 0; i < want.length; i++) {
          for (const k of ['open', 'high', 'low', 'close']) {
            const limit = ATOL + RTOL * Math.abs(want[i][k]);
            assert.ok(
              Math.abs(out[i][k] - want[i][k]) <= limit,
              `${c.id}.bars[${i}].${k}: got ${out[i][k]}, want ${want[i][k]}`
            );
          }
          assert.equal(out[i].time, want[i].time, `${c.id}.bars[${i}].time`);
          assert.equal(out[i].volume, want[i].volume, `${c.id}.bars[${i}].volume`);
        }
        continue;
      }
      // single-series kernels return the array itself; multi-series ones
      // return an object keyed by series name
      compareSeries(c.id, name, name === 'values' ? out : out[name], want);
    }
  });
}

test('golden: summary', () => {
  // Coverage is derived from the module's own exports, not counted: every
  // exported math kernel must have at least one fixture, and every fixture
  // fn must be a real exported kernel. A swapped-out kernel or a duplicate
  // case can no longer hide behind the case count.
  const isKernel = (k) => (/^calc[A-Z]/.test(k) || k === 'shapeSearch') && typeof core[k] === 'function';
  const exported = new Set(Object.keys(core).filter(isKernel));
  const covered = new Set(cases.map((c) => c.fn));
  const missing = [...exported].filter((k) => !covered.has(k));
  const unknown = [...covered].filter((k) => !exported.has(k));
  assert.deepEqual(unknown, [], 'fixtures reference kernels core.js does not export');
  assert.deepEqual(
    missing,
    [],
    'exported kernels without golden vectors — add a reference in tests/golden/generate.py, ' +
      'regenerate, and extend CLOSE_BASED if it takes plain values'
  );

  const top = drifts.slice().sort((a, b) => b.ratio - a.ratio).slice(0, 3);
  const used = top.length ? top[0].ratio : 0;
  console.log(
    `golden: ${cases.length} cases, ${exported.size}/${exported.size} kernels covered, ` +
      `vs ${meta.generated} fixtures — worst tolerance use ${(used * 100).toFixed(4)}% of limit` +
      (top.length ? ` (${top.map((d) => `${d.id} ${d.ratio.toExponential(1)}`).join(', ')})` : '')
  );
  assert.ok(used < 0.5, `drift crept above half the tolerance — investigate before it fails`);
});
